FROM node:14
WORKDIR /
COPY public /opt/angular-python-pi/public
COPY *.json /opt/angular-python-pi/
COPY startup.sh /opt/angular-python-pi/startup.sh
COPY *.js /opt/angular-python-pi/
COPY *.py /opt/angular-python-pi/
CMD ./opt/angular-python-pi/startup.sh
EXPOSE 8443 9443